// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-bDqaVGZmESyC-lCjIY_OkgSkZSXKRD0',
    appId: '1:686667962875:web:3d0fb0f07a951871fd535e',
    messagingSenderId: '686667962875',
    projectId: 'cico-8298b',
    authDomain: 'cico-8298b.firebaseapp.com',
    storageBucket: 'cico-8298b.appspot.com',
    measurementId: 'G-K2S4DN0XGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMPfEIUvpQY-mpVKxZ9Z6oEjTBNseoD0',
    appId: '1:686667962875:android:0eb5e6dc041f1ac2fd535e',
    messagingSenderId: '686667962875',
    projectId: 'cico-8298b',
    storageBucket: 'cico-8298b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCjgnz2YDOqOYj9SyFgInkr_DlQKFJ7Hc',
    appId: '1:686667962875:ios:024306c8a963da5afd535e',
    messagingSenderId: '686667962875',
    projectId: 'cico-8298b',
    storageBucket: 'cico-8298b.appspot.com',
    androidClientId: '686667962875-eltqhponek2lqlajfqugraobm2lan4o5.apps.googleusercontent.com',
    iosClientId: '686667962875-66o2aal7hsm9pcf34o15qu839tqgkqpd.apps.googleusercontent.com',
    iosBundleId: 'com.cico.checkInWebMobileExplore',
  );
}
